### create user
POST http://localhost:3333/user
content-type: application/json

{
	"name":"user16",
	"email":"user16@email.com",
	"password":"teste123@",
	"emailVerified": "2023-03-21T13:00:00.000Z",
  "image": "url_img",
  "role": "USER",
  "isTwoFactorEnabled": false
}


### Auth
POST http://localhost:3333/auth
content-type: application/json

{
	"email":"user2@email.com",
	"password":"teste123@"
}

### get orders
GET http://localhost:3333/list-user


###
POST http://localhost:3333/auth/refresh
content-type: application/json

{
	"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjODRmNjBiLTdjMjktNDIyOS1hOGI3LWQwMTQ4MjMxOGMxMCIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZW1haWwuY29tIiwiaWF0IjoxNzA0NjgyODIzLCJleHAiOjE3MDQ3NjkyMjN9.bsbjnDULrgyOC-emVHbP8Mx8GMXCR3fvWejq5iHHjxo"
}

### logout
POST http://localhost:3333/auth/logout